(()=>{'use strict';
const $=id=>document.getElementById(id);
const stages=[
{tag:'TEXT PREPARATION · NO NEURAL WEIGHTS',title:'First, make the words readable to the model.',description:'The tokenizer divides your prompt into vocabulary tokens and maps them to token IDs. This is preparation, not image generation. A token may be a word, part of a word, or punctuation.',takeaway:'Changing the prompt changes the input tokens. It does not retrain the model.',input:'“Luminous turquoise coral”',output:'A sequence of token IDs',file:'Tokenizer vocabulary and configuration'},
{tag:'LEARNED WEIGHTS · TEXT ENCODER',title:'Turn tokens into useful numerical context.',description:'The text encoder processes token IDs into a sequence of numerical representations. These embeddings carry contextual information that guides the denoising network. They are neither visible pixels nor a literal lookup of a stored picture.',takeaway:'The encoder’s weights stay fixed during LiveGrid inference; its output changes with your prompt.',input:'Token IDs',output:'Prompt embeddings',file:'sd-turbo-text-encoder.zip'},
{tag:'LEARNED WEIGHTS · U-NET',title:'Guide noisy latent values toward an image.',description:'The U-Net processes latent noise using the prompt embeddings and timestep. Its prediction, together with the scheduler update, produces a denoised latent representation. SD-Turbo is distilled to work in very few steps; LiveGrid uses one.',takeaway:'A different noise input can produce a different result even when the prompt and weights are unchanged.',input:'Latent noise + embeddings + timestep',output:'Prediction used to update the latent',file:'sd-turbo-unet.zip'},
{tag:'LEARNED WEIGHTS · VAE',title:'Decode the latent into visible pixels.',description:'The variational autoencoder contains an encoder and a decoder. This text-to-image workflow uses the decoder to turn the compact latent representation into a 512 × 512 image. The archive includes the full VAE weights.',takeaway:'Latents are numerical representations—not tiny JPEGs waiting to be enlarged.',input:'Denoised latent representation',output:'512 × 512 RGB image',file:'sd-turbo-config-and-vae.zip'},
{tag:'APPLICATION LOGIC · NO NEW MODEL WEIGHTS',title:'Turn generated frames into your projection atlas.',description:'LiveGrid blends successive images, enlarges the result to 1080 × 1080, applies gaps and brightness, and publishes a Spout stream. TouchDesigner can receive it and route it to MadMapper locally or over NDI.',takeaway:'The 100-square layout is a composition step. It does not require 100 copies of the model.',input:'Successive generated images',output:'One 10 × 10 atlas / live video feed',file:'LiveGrid application; separate from the weights'}];
function stage(i){document.querySelectorAll('[data-stage]').forEach((b,n)=>b.setAttribute('aria-pressed',n===i));const d=stages[i];for(const [id,key] of Object.entries({'stage-tag':'tag','stage-title':'title','stage-description':'description','stage-takeaway':'takeaway','stage-in':'input','stage-out':'output','stage-file':'file'}))$(id).textContent=d[key]}
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>stage(Number(b.dataset.stage)));stage(0);
const tabs=[...document.querySelectorAll('[role=tab]')];
function selectTab(id,focus=false){tabs.forEach(b=>{let active=b.getAttribute('aria-controls')===id;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;$(b.getAttribute('aria-controls')).hidden=!active;if(active&&focus)b.focus()})}
tabs.forEach((b,i)=>{b.onclick=()=>selectTab(b.getAttribute('aria-controls'));b.onkeydown=e=>{let j;if(e.key==='ArrowRight')j=(i+1)%tabs.length;if(e.key==='ArrowLeft')j=(i+tabs.length-1)%tabs.length;if(e.key==='Home')j=0;if(e.key==='End')j=tabs.length-1;if(j!==undefined){e.preventDefault();selectTab(tabs[j].getAttribute('aria-controls'),true)}}});
document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{selectTab(b.dataset.next,true);$('tab-'+b.dataset.next).scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})});
const sigmoid=z=>1/(1+Math.exp(-z));const grid=$('neuron-grid');for(let i=0;i<100;i++)grid.appendChild(document.createElement('span'));
function renderNeuron(message){const x=Number($('feature').value),n=Number($('noise').value),w=Number($('weight').value),z=w*x-.4*n-.1,y=sigmoid(z),loss=.5*(y-.9)**2;for(const id of ['feature','noise','weight'])$(id+'-value').textContent=Number($(id).value).toFixed(2);$('formula').textContent=`z = (${w.toFixed(2)} × ${x.toFixed(2)}) + (−0.40 × ${n.toFixed(2)}) − 0.10\ny = sigmoid(z) = 1 / (1 + e⁻ᶻ)`;$('activation').textContent=y.toFixed(3);$('loss').textContent=loss.toFixed(4);[...grid.children].forEach((cell,i)=>{let local=i===0?n:Math.max(-1,Math.min(1,n+.75*Math.sin(i*1.618)));cell.style.opacity=(.05+.95*sigmoid(w*x-.4*local-.1)).toFixed(4)});if(message)$('experiment-message').textContent=message;return{x,w,y,loss}}
for(const id of ['feature','noise'])$(id).oninput=()=>renderNeuron('Inference: the inputs changed. The weights stayed fixed.');$('weight').oninput=()=>renderNeuron('You edited a weight: the rule for interpreting x₁ changed. This is a manual edit, not training.');
$('learn-step').onclick=()=>{let old=renderNeuron();let delta=.5*(.9-old.y)*old.y*(1-old.y)*old.x;$('weight').value=Math.max(-3,Math.min(3,old.w+delta));let next=renderNeuron();renderNeuron(old.x===0?'No update: x₁ is zero, so changing its weight cannot affect this output.':next.w===old.w?'No visible update at this slider precision or boundary. Try a larger x₁ or a lower weight.':`Toy training: w₁ changed from ${old.w.toFixed(2)} to ${next.w.toFixed(2)}. Error went from ${old.loss.toFixed(4)} to ${next.loss.toFixed(4)}. Real LiveGrid inference does not perform this update.`)};
$('reset-neuron').onclick=()=>{$('feature').value=.8;$('noise').value=.2;$('weight').value=.5;renderNeuron('Reset. Move an input first; the weight stays at 0.50.')};renderNeuron();
const components=[{name:'U-Net',values:865910724},{name:'Text encoder',values:340387840},{name:'VAE',values:83653863}];
function memory(){const bits=Number(document.querySelector('[name=precision]:checked').value),copies=Number($('copies').value),total=components.reduce((s,c)=>s+c.values,0)*bits/8*copies;$('copies-value').textContent=copies;$('total-storage').textContent=(total/1e9).toFixed(2)+' GB · '+(total/2**30).toFixed(2)+' GiB';$('memory-bars').replaceChildren();components.forEach(c=>{let bytes=c.values*bits/8*copies;let row=document.createElement('div');row.className='bar-row';let label=document.createElement('div');label.className='bar-label';let name=document.createElement('span');name.textContent=c.name;let value=document.createElement('span');value.textContent=(bytes/1e9).toFixed(2)+' GB · '+(bytes/total*100).toFixed(1)+'%';label.append(name,value);let track=document.createElement('div');track.className='bar-track';let fill=document.createElement('div');fill.className='bar-fill';fill.style.width=(bytes/total*100)+'%';track.append(fill);row.append(label,track);$('memory-bars').append(row)});$('memory-note').textContent=bits===16?`fp16 is the actual stored format. ${copies===1?'One copy matches LiveGrid’s architecture.':copies+' separate copies are hypothetical; LiveGrid loads one.'} These totals exclude file headers and runtime overhead.`:`${bits}-bit is a storage comparison only, not an available LiveGrid setting. ${bits===8?'Actual quantized models may need extra scales and metadata. ':''}This does not predict quality, speed, or total VRAM.`}
document.querySelectorAll('[name=precision]').forEach(r=>r.onchange=memory);$('copies').oninput=memory;memory();
const questions=[{q:'You change “coral” to “liquid chrome.” What changes?',answers:['The model weights are retrained.','The input and prompt embeddings change.'],correct:1,why:'During inference, the pretrained weights stay fixed. The model computes different embeddings from the new prompt.'},{q:'The grid has 100 squares. How many model streams does this LiveGrid version generate?',answers:['One stream, composed into 100 cells.','100 separately prompted streams.'],correct:0,why:'Mosaic and Repeat are layout operations on one generation stream. They do not create 100 models.'},{q:'You have the U-Net ZIP. Can it run the complete pipeline by itself?',answers:['Yes; the other ZIPs are optional styles.','No; all three ZIPs provide required components.'],correct:1,why:'Text encoding, denoising, decoding, tokenization, and configuration work together. These downloads are components, not alternative styles.'},{q:'A tensor checksum matches the upstream model. What does that establish?',answers:['The downloaded tensor file matches that upstream file.','The model’s training data contains no personal information.'],correct:0,why:'A checksum verifies file identity, not training-data provenance or privacy. These are unmodified pretrained weights, not an audit of their training data.'}];
let solved=new Set();function renderQuiz(){solved.clear();$('questions').replaceChildren();questions.forEach((q,i)=>{let section=document.createElement('article');section.className='question';let title=document.createElement('h3');title.textContent=(i+1)+'. '+q.q;let answers=document.createElement('div');answers.className='answers';let feedback=document.createElement('p');feedback.className='feedback';feedback.setAttribute('aria-live','polite');q.answers.forEach((a,j)=>{let button=document.createElement('button');button.textContent=a;button.setAttribute('aria-pressed','false');button.onclick=()=>{[...answers.children].forEach(b=>b.setAttribute('aria-pressed',b===button));let correct=j===q.correct;feedback.textContent=(correct?'Correct. ':'Try again. ')+q.why;if(correct)solved.add(i);else solved.delete(i);$('quiz-progress').textContent=solved.size===4?'4 of 4. You can now distinguish weights, inputs, pipeline components, and file verification.':`${solved.size} of 4 concepts checked.`};answers.append(button)});section.append(title,answers,feedback);$('questions').append(section)});$('quiz-progress').textContent='0 of 4 concepts checked.'}$('quiz-reset').onclick=renderQuiz;renderQuiz();
})();
